<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Invoice No: #{{ $invoice->id }}</title>

    <style>
        body {
            font-family: Helvetica, sans-serif;
            font-size: 13px;
        }

        .container {
            max-width: 680px;
            margin: 0 auto;
        }

        .logotype {
            background: url(https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Bollore_Logistics_Logo.png/1280px-Bollore_Logistics_Logo.png);
            color: #fff;
            width: 75px;
            height: 75px;
            line-height: 75px;
            text-align: center;
            font-size: 11px;
        }

        .column-title {
            background: #eee;
            text-transform: uppercase;
            padding: 15px 5px 15px 15px;
            font-size: 11px
        }

        .column-detail {
            border-top: 1px solid #eee;
            border-bottom: 1px solid #eee;
        }

        .column-header {
            background: #eee;
            text-transform: uppercase;
            padding: 15px;
            font-size: 11px;
            border-right: 1px solid #eee;
        }

        .row {
            padding: 7px 14px;
            border-left: 1px solid #eee;
            border-right: 1px solid #eee;
            border-bottom: 1px solid #eee;
        }

        .alert {
            background: #ffd9e8;
            padding: 20px;
            margin: 20px 0;
            line-height: 22px;
            color: #333
        }

        .socialmedia {
            background: #eee;
            padding: 20px;
            display: inline-block
        }
    </style>
</head>

<body>
    <div class="container">

        <table width="100%">
            <tr>
                <td style="vertical-align: text-top;">
                    <div
                        style="background: transparent url({{ env('APP_URL') }}/logo.png);width: 150px;height: 150px;background-position: center;background-size: 160px;">
                    </div>
                </td>
                <td width="300px">
                    <div
                        style="background: #17046d; color:#fff;padding-left: 30px;font-size: 24px;font-weight: bold;letter-spacing: -1px;height: 73px;line-height: 75px;">
                        Invoice No. #{{ sprintf('%04d', $invoice->id) }}</div>
                </td>
                <td></td>
            </tr>
        </table>
        <br><br>
        {{-- <h3>Your contact details</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p><br> --}}
        <table width="100%" style="border-collapse: collapse;">
            <tr>
                <td width="50%" style="background:#eee;padding:20px;">
                    <strong>Date:</strong>
                    {{ Carbon\Carbon::parse($invoice->created_at)->format('jS F, Y h:i A') }}<br>
                    {{-- <strong>Payment type:</strong> Credit Card VISA<br> --}}
                    <strong>Delivery type:</strong> STANDARD<br>
                    <strong>Generated By:</strong> {{ $invoice->user->name }}<br>
                </td>
                <td style="background:#eee;padding:20px;">
                    <strong>Sale-No:</strong> {{ $invoice->sale_id }}<br>
                    <strong>Customer's Name:</strong> {{ $invoice->sale->customer->name }}<br>
                    <strong>E-mail:</strong> {{ $invoice->sale->customer->email }}<br>
                    <strong>Phone:</strong> {{ $invoice->sale->customer->phone_number }}<br>
                </td>
            </tr>
        </table><br>
        {{-- <table width="100%">
            <tr>
                <td>
                    <table>
                        <tr>
                            <td style="vertical-align: text-top;">
                                <div
                                    style="background: #ffd9e8 url(https://cdn0.iconfinder.com/data/icons/commerce-line-1/512/comerce_delivery_shop_business-07-128.png);width: 50px;height: 50px;margin-right: 10px;background-position: center;background-size: 42px;">
                                </div>
                            </td>
                            <td>
                                <strong>Delivery</strong><br>
                                Firstname Lastname<br>
                                Queens high 17 B<br>
                                SE-254 57 Helsingborg<br>
                                Sweden
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    <table>
                        <tr>
                            <td style="vertical-align: text-top;">
                                <div
                                    style="background: #ffd9e8 url(https://cdn4.iconfinder.com/data/icons/app-custom-ui-1/48/Check_circle-128.png) no-repeat;width: 50px;height: 50px;margin-right: 10px;background-position: center;background-size: 25px;">
                                </div>
                            </td>
                            <td>
                                <strong>Delivery</strong><br>
                                Firstname Lastname<br>
                                Queens high 17 B<br>
                                SE-254 57 Helsingborg<br>
                                Sweden
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table><br> --}}
        {{-- <table width="100%" style="border-top:1px solid #eee;border-bottom:1px solid #eee;padding:0 0 8px 0">
            <tr>
                <td>
                    <h3>Checkout details</h3>Your checkout made by VISA Card **** **** **** 2478
                <td>
            </tr>
        </table><br> --}}
        {{-- <div
            style="background: #ffd9e8 url(https://cdn4.iconfinder.com/data/icons/basic-ui-2-line/32/shopping-cart-shop-drop-trolly-128.png) no-repeat;width: 50px;height: 50px;margin-right: 10px;background-position: center;background-size: 25px;float: left; margin-bottom: 15px;">
        </div> --}}
        <h3>Your Items</h3>

        <table width="100%" style="border-collapse: collapse;border-bottom:1px solid #eee;">
            <tr>
                <td width="40%" class="column-header">Item Description</td>
                <td width="20%" class="column-header">Quantity</td>
                <td width="20%" class="column-header">Unit Price</td>
                <td width="20%" class="column-header">Total Price</td>
            </tr>

            @php
                $total_count = 0;
                $total_cost = 0;
            @endphp
            @foreach (App\Models\ProductDescription::all() as $product)
                @php
                    $count = 0;
                    $cost = 0;
                @endphp
                @foreach ($invoice->sale->productItems as $item)
                    @if ($product->id == $item->product_description_id)
                        @php
                            $cost += $item->pivot->sale_price;
                            $count++;
                            $total_count++;
                            $total_cost += $item->pivot->sale_price;
                        @endphp
                    @endif
                @endforeach


                @if ($count > 0)
                    <tr>
                        <td class="row"><span
                                style="color:#777;font-size:11px;">#{{ $product->id }}</span><br>{{ $product->title }}
                            - {{ $product->quantity }}{{ $product->unit->symbol }}</td>
                        <td class="row">{{ $count }}</td>
                        <td class="row"><span style="color:#777">
                                <x-currency></x-currency>
                            </span>{{ number_format($cost / $count, 2) }}</td>
                        <td class="row" style="text-align:right"><span style="color:#777">
                                <x-currency></x-currency>
                            </span>{{ number_format($cost, 2) }}</td>
                    </tr>
                @endif
            @endforeach
        </table><br>
        <table width="100%">
            <tr>
                <td>
                    <table width="300px" style="float:right">
                        <tr>
                            <td><strong>Sub-total:</strong></td>
                            <td style="text-align:right"><span style="color:#777">
                                    <x-currency></x-currency>
                                </span>{{ number_format($total_cost, 2) }}</td>
                        </tr>
                        <tr>
                            <td><strong>Shipping fee:</strong></td>
                            <td style="text-align:right"><span style="color:#777">
                                    <x-currency></x-currency>
                                </span>{{ number_format(0, 2) }}</td>
                        </tr>
                        <tr>
                            <td><strong>VAT 16%:</strong></td>
                            <td style="text-align:right"><span style="color:#777">
                                    <x-currency></x-currency>
                                </span>{{ number_format($total_cost, 2) }}</td>
                        </tr>
                        <tr>
                            <td><strong>Grand total:</strong></td>
                            <td style="text-align:right"><span style="color:#777">
                                    <x-currency></x-currency>
                                </span>{{ number_format($total_cost, 2) }}</td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <br>
        <h1 style="color: #17046d">Thank You for Your Business!!</h1>

    </div><!-- container -->
</body>

</html>
