<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Order No: #{{ $order->id }}</title>

    <style>
        body {
            font-family: Calibri, Candara, Segoe, Segoe UI, Optima, Arial, sans-serif;
            font-size: 13px;
        }

        .container {
            max-width: 680px;
            margin: 0 auto;
        }

        .logotype {
            background: url(https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Bollore_Logistics_Logo.png/1280px-Bollore_Logistics_Logo.png);
            color: #fff;
            width: 75px;
            height: 75px;
            line-height: 75px;
            text-align: center;
            font-size: 11px;
        }

        .column-title {
            background: #eee;
            text-transform: uppercase;
            padding: 15px 5px 15px 15px;
            font-size: 11px
        }

        .column-detail {
            border-top: 1px solid #eee;
            border-bottom: 1px solid #eee;
        }

        .column-header {
            background: #eee;
            text-transform: uppercase;
            padding: 15px;
            font-size: 11px;
            border-right: 1px solid #eee;
        }

        .row {
            padding: 7px 14px;
            border-left: 1px solid #eee;
            border-right: 1px solid #eee;
            border-bottom: 1px solid #eee;
        }

        .alert {
            background: #ffd9e8;
            padding: 20px;
            margin: 20px 0;
            line-height: 22px;
            color: #333
        }

        .socialmedia {
            background: #eee;
            padding: 20px;
            display: inline-block
        }
    </style>
</head>

<body>
    <div class="container">

        <table width="100%">
            <tr>
                <td style="vertical-align: text-top;">
                    <div
                        style="background: transparent url({{ env('APP_URL') }}/logo.png);width: 120px;height: 120px;background-position: center;background-size: 120px;">
                    </div>
                </td>
                <td width="300px">
                    <div
                        style="background: transparent; color:black;padding-left: 30px;font-size: 16px;font-weight: medium;letter-spacing: -1px;height: 73px;line-height: 75px;">
                        Purchase Order
                        ALPS/LC/{{ Carbon\Carbon::parse($order->created_at)->format('y') }}/{{ sprintf('%04d', $order->id) }}
                    </div>
                </td>
                <td></td>
            </tr>
        </table>
        <br><br>
        <table width="100%" style="border-collapse: collapse;">
            <tr>
                <td width="50%" style="background:#eee;padding:20px;">
                    <strong>Date:</strong>
                    {{ Carbon\Carbon::parse($order->created_at)->format('jS F, Y h:i A') }}<br>
                    {{-- <strong>Payment type:</strong> Credit Card VISA<br> --}}
                    <strong>Delivery type:</strong> STANDARD<br>
                    <strong>Generated By:</strong> {{ $order->user->name }}<br>
                </td>
                <td style="background:#eee;padding:20px;">
                    <strong>Suppliers's Name:</strong> {{ $order->supplier->name }}<br>
                    <strong>E-mail:</strong> {{ $order->supplier->email }}<br>
                    <strong>Phone:</strong> {{ $order->supplier->phone_number }}<br>
                </td>
            </tr>
        </table><br>

        <table width="100%" style="border-collapse: collapse;border-bottom:1px solid #eee;">
            <tr>
                <td width="40%" class="column-header">Item Description</td>
                <td width="20%" class="column-header">Quantity</td>
                <td width="20%" class="column-header">Unit Price</td>
                <td width="20%" class="column-header">Total Price</td>
            </tr>

            @php
                $total_cost = 0;
            @endphp
            @foreach ($order->productDescriptions as $product)
                <tr>
                    <td class="row">
                        <span style="color:#777;font-size:11px;">#{{ $product->id }}</span><br>
                        <small><span style="color:#1575bb">{{ $product->brand->name !='Miscellaneous'? $product->brand->name:'' }}</span> {{ $product->title }} - {{ $product->quantity }}{{ $product->unit->symbol }}</small>
                    </td>
                    <td class="row">{{ $product->pivot->quantity }}</td>
                    <td class="row"><span style="color:#777">
                            <x-currency></x-currency>
                        </span>{{ number_format($product->price, 2) }}</td>
                    <td class="row" style="text-align:right"><span style="color:#777">
                            <x-currency></x-currency>
                        </span>{{ number_format($product->price * $product->pivot->quantity, 2) }}</td>
                </tr>

                @php
                    $total_cost += $product->price * $product->pivot->quantity;
                @endphp
            @endforeach

        </table><br>
        <table width="100%">
            <tr>
                <td>
                    <table width="300px" style="float:right">
                        <tr>
                            <td colspan="3" style="font-size:20px"><strong>Grand total:</strong></td>
                            <td style="text-align:right;font-size:20px">
                                <span style="color:#777">
                                    <x-currency></x-currency>
                                </span>{{ number_format($total_cost, 2) }}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <br>
        <br>
        <br>
        <br>
        <br>
        <table width="100%"
            style="border-collapse: collapse;border-bottom:1px solid #eee; border-top:2px solid #1575bb">

            <tr>
                <td class="row">
                    Prepared By:
                </td>
                <td class="row">
                    <span style="color:#777">
                        <sup><small>Name</small></sup>
                    </span>
                    {{ $order->user->name }}
                </td>
                <td class="row">
                    <span style="color:#777">
                        <sup><small>Signature</small></sup>
                    </span>
                    ________________________
                </td>
                <td class="row"><span style="color:#777">
                        <sup><small>Date</small></sup>
                    </span>
                    ______________________
                </td>
            </tr>
            <tr>
                <td class="row">
                    Approved By:
                </td>
                <td class="row">
                    <span style="color:#777">
                        <sup><small>Accountant's Name</small></sup>
                    </span>
                    _______________________
                </td>
                <td class="row">
                    <span style="color:#777">
                        <sup><small>Signature</small></sup>
                    </span>
                    ________________________
                </td>
                <td class="row"><span style="color:#777">
                        <sup><small>Date</small></sup>
                    </span>
                    ______________________
                </td>
            </tr>
            <tr>
                <td class="row">
                    Authorized By:
                </td>
                <td class="row">
                    <span style="color:#777">
                        <sup><small>Manager's Name</small></sup>
                    </span>
                    _______________________
                </td>
                <td class="row">
                    <span style="color:#777">
                        <sup><small>Signature</small></sup>
                    </span>
                    ________________________
                </td>
                <td class="row"><span style="color:#777">
                        <sup><small>Date</small></sup>
                    </span>
                    ______________________
                </td>
            </tr>


        </table>


    </div><!-- container -->
    <br>
    <br>
    <br>
    <br>
    <h2 style="color: #1575bb; text-align:center">Thank You for Your Business!!</h2>
</body>

</html>
