<div>
    <div class="container-fluid">
        <x-page-heading>Invoices List</x-page-heading>

        <div class="card my-5">
            <div class="table-responsive">
                @if ($invoices->count() > 0)
                    <table class="table table-striped table-hover table-bordered align-middle">
                        <thead class="">
                            <tr>
                                <th>ID</th>
                                <th>Generated By</th>
                                <th>Sale ID</th>
                                <th>Amount</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            @foreach ($invoices as $invoice)
                                <tr class="">
                                    <td scope="row">{{ $invoice->id }}</td>
                                    <td>{{ $invoice->user->name }}</td>
                                    <td>{{ $invoice->sale_id }}</td>
                                    <td>
                                        <x-currency></x-currency>{{ number_format($invoice->amount, 2) }}
                                    </td>
                                    <td>
                                        <div class="d-flex flex-row justify-content-center">
                                            <button
                                                onclick="confirm('Are you Sure you want to delete this Invoice?')||event.stopImmediatePropagation()"
                                                wire:click="delete({{ $invoice->id }})"
                                                class="btn btn-danger flex-col mx-2">
                                                <i class="fas fa-trash"></i>
                                            </button>

                                            <a href="{{ route('admin.invoices.show', $invoice->id) }}" target="_blank" class="btn btn-dark"><i class="fas fa-file-pdf"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                @else
                    <h4 class="text-center py-5">You have not generated any Invoices</h4>
                @endif
            </div>

        </div>
    </div>
</div>
